[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  # Ensure proper bundling of dependencies
  node_bundler = "esbuild"
  # Include source maps for better error tracking
  included_files = ["netlify/functions/**/*.ts"]

[dev]
  command = "npm run dev"
  port = 8889
  targetPort = 3001
  publish = ".next"
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200